config/routes.rb
Rails.application.routes.draw do
  authenticated do
    root 'expenditures#index'
  end

  root 'pages#welcome'

  resources :expenditures

  devise_for :users,
    controllers: { registrations: 'registrations' },
    skip: [:session, :registration]

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session

    get 'signup', to: 'registrations#new', as: :new_user_registration
    post 'signup', to: 'registrations#create', as: :user_registration
    get 'profile/edit', to: 'registrations#edit', as: :edit_user_registration
    patch 'profile/edit', to: 'registrations#update'
    delete 'profile/edit', to: 'registrations#destroy'
  end

  scope '/profile' do
    resources :user_categories, controller: :categories, only: %i[index create destroy]
  end
 # get 'profile/custom_categories', to: 'categories#user_categories', as: :user_categories
 # post 'profile/custom_categories', to: 'categories#user_categories'
 # match 'profile/custom_categories' => 'categories#users_categories', as: :user_cateogories, via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent_category, class_name: 'Category', foreign_key: 'parent_id', optional: true
  belongs_to :user, foreign_key: true, optional: true

  has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id'
  has_many :expenditures

  validates :name, presence: true, length: { in: 2..30 }
  validates :parent_id, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true
  validate :parent_category_existence
  validate :category_nesting_level

  def self.parent_categories
    @parent_categories ||= Category.where(parent_id: nil).where.not(name: 'Uncategorised')
  end

  def base_category?
    user_id == nil
  end

  def subcategories
    subcategories
  end

  private

  def parent_category_existence
    if parent_id? && parent_id > 0 && parent_category.nil?
      errors.add(:parent_category, 'should exist')
    end
  end

  def category_nesting_level
    if parent_id? && parent_id > 0 && parent_category.present? && parent_category.parent_id?
      errors.add(:parent_category, 'should not be a subcategory')
    end
  end
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  scope :users_expenditures, ->(user) { where(user_id: user.id).joins(:category) }

  belongs_to :category
  belongs_to :user

  validates :amount, numericality: { bigger_or_equal_than: 0, lower_than: 100000 }, allow_nil: true
  validates :title, length: { maximum: 50 }, allow_blank: true

  before_validation :set_defaults

  def self.search(search)
    if search
      where('cast(amount as text) ILIKE :search OR title ILIKE :search OR name ILIKE :search OR cast(date as text) ILIKE :search', search: "%#{search}%")
    else
      all
    end
  end

  def self.order_by(column, direction)
    order(
      Arel.sql("#{column} #{direction}"),
      date: :desc,
      created_at: :desc
    )
  end

  private

  def set_defaults
    self.amount ||= 0
    self.title = "Untitled" if title.empty?
    self.category_id ||= "1"
    self.date ||= Time.zone.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :expenditures, dependent: :destroy
  has_many :categories, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :name, presence: true, length: { in: 3..30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @user_categories = current_user.categories
    @custom_category = Category.new
    @categories = Category.parent_categories
  end

  def create
    @custom_category = Category.new(category_params)
    @custom_category.user_id = current_user.id
    @custom_category.save

    redirect_back(fallback_location: user_categories_path)
  end

  def destroy
    @user_category = Category.find(params[:id])
    @user_category.destroy

    redirect_back(fallback_location: user_categories_path)
  end

  private

  def category_params
    params.require(:category).permit(:parent_id, :name)
  end
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :set_expenditure, only: %i[edit update destroy]
  before_action :set_categories, only: %i[edit new]
  before_action :authenticate_user!

  def index
    @expenditures = Expenditure
      .users_expenditures(current_user)
      .search(params[:search])
      .order_by(case_insensitive(sort_column), sort_direction)
  end

  def new
    @expenditure = Expenditure.new

    respond_to do |format|
      format.html { render partial: 'form' }
      format.js { render 'form' }
    end
  end

  def create
    @expenditure = Expenditure.new(expenditure_params)
    @expenditure.user_id = current_user.id

    respond_to do |format|
      if @expenditure.save
        format.html { redirect_back(fallback_location: expenditures_path) }
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.html { render partial: 'form' }
      format.js { render 'form' }
    end
  end

  def update
    @expenditure.update(expenditure_params)

    respond_to do |format|
      format.html { redirect_back(fallback_location: expenditures_path) }
      format.js
    end
  end

  def destroy
    respond_to do |format|
      if @expenditure.destroy
        format.html { redirect_back(fallback_location: expenditures_path) }
        format.js
      end
    end
  end

  private

  def expenditure_params
    params.require(:expenditure).permit(:amount, :title, :category_id, :date)
  end

  def set_expenditure
    @expenditure = Expenditure.find(params[:id])
  end

  def set_categories
    @categories = Category.parent_categories
  end

  def sort_column
    return 'categories.name' if params[:column] == 'category_id'
    Expenditure.column_names.include?(params[:column]) ? params[:column] : 'date'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def case_insensitive(column)
    %w[title category].include?(column) ? "lower(#{column})" : column
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    errors_count = resource.errors.count

    html = <<-HTML
      <div class="alert alert-danger col-4">
        <div id="error_explanation">
          <h5 class="alert-heading">#{pluralize(errors_count, 'error')}:</h5>
          <ul>#{messages}</ul>
        </div>
      </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/expenditure_helper.rb
module ExpenditureHelper
  def sort(column, title = nil)
    title ||= column.titleize
    direction = sort_direction_literal(column)
    icon = sort_icon(column)
    link_to "#{title}#{icon}", sorting_params(column, direction)
  end

  private

  def sort_direction_literal(column)
    column == params[:column] && sort_direction == 'asc' ? 'desc' : 'asc'
  end

  def sort_icon(column)
    return '' if column != params[:column]

    sort_direction == 'asc' ? '▲' : '▼'
  end

  def sorting_params(column, direction)
    params.permit(:column, :direction, :search)
      .merge(column: column, direction: direction)
  end
end

app/views/categories/index.html.erb
<div class="row justify-content-center">
  <div class="col-4">
    Your custom categories
    <table>
      <thead>
        <th>Parent category</th>
        <th>Name</th>
      </thead>
      <tbody>
        <% @user_categories.each do |category| %>
          <tr>
            <td><%= category.parent_category.name %></td>
            <td><%= category.name %></td>
            <td><%= link_to 'delete', user_category_path(category), method: :delete %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-2">
    <%= form_for @custom_category, url: user_categories_path do |f| %>
      <div class="form-group">
      <%= f.label :parent_id %>
      <%= f.collection_select :parent_id,
        @categories,
        :id, :name,
        {},
        { class: "form-control custom-select" } %>
      </div>

      <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      </div>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/expenditures/_expenditure.html.erb
<tr id=<%= "expenditure_#{expenditure.id}" %>>
  <td class="align-middle"><%= ActionController::Base.helpers.number_to_currency(expenditure.amount) %></td>
  <td class="align-middle"><%= expenditure.title %></td>
  <td class="align-middle"><%= expenditure.category.name unless expenditure.category.nil? %></td>
  <td class="align-middle"><%= expenditure.date %></td>
  <td class="align-middle">
    <%= link_to "edit",
      edit_expenditure_path(expenditure),
      class: "btn btn-edit btn-sm",
      remote: true,
      'data-disable-with' => fa_icon('spinner spin').html_safe %>
    <%= link_to "delete",
      expenditure,
      method: :delete,
      class: "btn btn-danger btn-sm",
      remote: true,
      'data-disable-with' => fa_icon('spinner spin').html_safe %>
  </td>
</tr>

app/views/expenditures/_form.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="expenditure_modal"><%= "#{action_name.capitalize} #{controller_name.singularize}" %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<%= form_for @expenditure, html: { class: "needs-validation form-horizontal", novalidate: "novalidate" }, remote: true do |f| %>
  <div class="modal-body">
    <div class="form-row">
      <div class="form-group col-sm-5">
        <%= f.label :amount %>
        <%= f.number_field :amount,
          class: "form-control",
          min: "0",
          max: "999999.99",
          step: "0.01" %>
        <div class="invalid-feedback">
          <i>should be lower than 1,000,000</i>
        </div>
      </div>

      <div class="form-group col-sm-7">
        <%= f.label :category %>
        <%= f.grouped_collection_select :category_id,
          @categories, :subcategories, :name,
          :id, :name,
          { include_blank: true },
          { class: "form-control custom-select" } %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-sm-12">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", pattern: ".{0,50}" %>
      <div class="invalid-feedback">
        <i>should be shorter than 51 characters.</i>
      </div>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-sm-5">
        <%= f.label :date %>
        <%= f.text_field :date,
          value:  @expenditure.date || Time.zone.today,
          class: "form-control",
          id: "expenditure_date" %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button class: "btn btn-primary",
      'data-disable-with' => fa_icon('spinner spin', text: 'Please wait...').html_safe %>
  </div>
<% end %>

app/views/expenditures/_search.html.erb
      <%= form_tag expenditures_path, method: 'get', remote: true do %>
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :column, params[:column] %>
        <div class="form-row">
          <div class="col-sm-8 my-1">
            <%= text_field_tag :search, params[:search],
                                        class: "form-control form-control-sm"%>
          </div>
          <div class="col-auto my-1">
            <%= submit_tag "Search", name: nil,
                                     class: "btn btn-sm btn-primary" %>
          </div>
      </div>
      <% end %>

app/views/expenditures/_table.html.erb
  <table class="table table-sm table-hover" id="expenditures_table" style="width:100%">
    <thead class="thead-light">
      <tr id="sort">
        <th width="10%"><%= sort 'amount' %></th>
        <th width="43%"><%= sort 'title' %></th>
        <th width="25%"><%= sort 'category_id', 'Category' %></th>
        <th width="10%"><%= sort 'date' %></th>
        <th width="12%"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @expenditures %>
    </tbody>
  </table>

app/views/expenditures/create.js.erb
$("#modal-window").modal("hide");
  $('#expenditures_table > tbody')
    .prepend($('<%= j render @expenditure %>')
      .hide()
      .fadeIn('normal')
      .addClass('blink-green')
    );

app/views/expenditures/destroy.js.erb
$('tr#expenditure_<%= @expenditure.id %> > td:nth-child(5) > a.btn.btn-danger').replaceWith('<a class="btn btn-danger btn-sm">delete</a>');
$('#expenditure_<%= @expenditure.id %>')
  .animate({ backgroundColor: "#df4957", opacity: 0 }, 600, function (){
      $(this).remove();
    });

app/views/expenditures/form.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'form') %>");
$("#modal-window").modal();

$("#expenditure_date").datepicker({
  'firstDay': 1,
  'dateFormat': 'yy-mm-dd'
});

var form = $('form#new_expenditure');
var title = $('#expenditure_title');
form.on('submit', function (event) {
  if (form[0].checkValidity() === false || title.val().length >= 50 ) {
    event.preventDefault();
    event.stopPropagation();
  }
  form.addClass('was-validated');
});

app/views/expenditures/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-8">
      <div class="row justify-content-between">
        <div id="expenditures_search">
          <%= render 'search' %>
        </div>
        <%= link_to 'Add new expenditure', new_expenditure_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary', 'data-disable-with' => fa_icon('spinner spin', text: 'Please wait...').html_safe} %>
        <div id="modal-window" class="modal hide fade expenditure-modal" role="dialog" aria-labelledby="expenditure-modal" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="top10" id="expenditures">
          <%= render 'table' %>
        </div>
      </div>
    </div>
    <div class="col-2">
    </div>
  </div>
</div>

app/views/expenditures/index.js.erb
$('#expenditures').html('<%= j render 'table' %>');

// update sort params in search form
$('#column').val('<%= j params[:column] %>');
$('#direction').val('<%= j params[:direction] %>');

app/views/expenditures/show.html.erb
<% provide(@expenditure) %>
<ul>
  <li><%= @expenditure.amount %></li>
  <li><%= @expenditure.title %></li>
  <li><%= @expenditure.category %></li>
</ul>

app/views/expenditures/update.js.erb
$("#modal-window").modal("hide");
$('#expenditure_<%= @expenditure.id %>').replaceWith('<%= j render @expenditure %>');
$('#expenditure_<%= @expenditure.id %>').addClass('blink-green');

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Budget tracker",
    root_path,
    class: "navbar-brand",
    style: "margin-right: 50px;" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <% if user_signed_in? %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span id="navbar-user-name" class="nav-text">
              Logged in as: <strong><%= current_user.name %></strong>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Your expenditures",
              expenditures_path,
              class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Settings",
              edit_user_registration_path,
              class: "dropdown-item" %>
            <%= link_to "Log out",
              destroy_user_session_path,
              method: :delete,
              class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    <% else %>
      <div class="navbar-nav ml-auto">
        <%= link_to "Log in",
          new_user_session_path,
          class: "btn btn-primary nav-btn",
          role: "button" %>
        <%= link_to "Sign up",
          new_user_registration_path,
          class: "btn btn-secondary nav-btn",
          style: "margin-left: 10px;",
          role: "button" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag '$.fx.off = true;' if Rails.env.test? %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <% flash.each do |key, value| %>
          <%= content_tag :p, value, class: "alert alert-danger flash #{key}" if key=='alert' %>
          <%= content_tag :p, value, class: "alert alert-success flash #{key}" if key=='notice' %>
        <% end %>
      </div>
    </div>
    <%= yield %>
    <div class="container">
      <div class="row justify-content-md-center">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
    </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<center>
  <div class="container center jumbotron">
    <h1>Welcome to the Budget Tracker</h1>

    <h5>Track your expenditures.</h5>
    <h5>Plan your budgets.</h5>

    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  </div>
</center>